### ISSUE TITLE
Support for white-list-based MUC avatars

### ISSUE THREAD

**Issue by muppeth** [horazont/muchopper#3]
Are there any plans to include MUC Avatar? This will greatly improve usability and looks of the website.

Btw, kudos for the directory. Very much appreciated.

**Comment by horazont** [comment]
No, not planned. Avatars have multiple issues:

- To deliver them properly even to mobile clients, we’d definitely have to enforce a maximum size, which requires parsing image data on a server. Which I don’t like, because image processing is notoriously bug-ridden including security issues.
- Even if we do that, the processed images would have to be stored somewhere, which would be one of my machines.
- If someone uses a legally questionable avatar (I don’t think I need to name explicit examples of what that could be, but I can), we need to have a procedure to remove those avatars and prevent them from re-appearing. And the capacities to deal with this legally.

So… This is a wontfix at the current state of affairs. It would need:

- A proper legal framework which releases me from any liability for the content there.
- A proper software framework which allows image processing in a reasonably safe manner (I do actually have such a thing, but it’s very cumbersome to use and to deploy, and it’s not worth the trouble).
- The manpower to deal with abuse.

**Comment by horazont** [comment]
We could probably operate this feature on a manual white-list basis. We would only do this for MUCs where the operators are well-known.

The question is whether this is politically a sane thing to do.

**Comment by wiktor-k** [comment]
Images can certainly be problematic but maybe whitelisting is a sane approach.

NB: Even the channel name can contain illegal stuff or links to such material, not mentioning such evil stuff as [illegal primes](https://en.wikipedia.org/wiki/Illegal_prime)!

**Comment by horazont** [comment]
We have basic countermeasures which prevent the illegal stuff to be interesting: We don’t actually convert any links in the listing to clickable links, and we limit the amount of content which can be put in either of these fields.

**Comment by wiktor-k** [comment]
:+1: good idea!

The whitelisting idea is also fine, although because XMPP is niche the problem is probably not as apparent now as it could be.

:wave:

**Comment by muppeth** [comment]
On one hand I dont see how images could be problematic, on the other hand unfortunately internet is full of people that would use any chance to exploit and troll. It's a pity that everyone has to suffer form the potential threat. 
Considering this might be rather rare situation, such rooms could be reported and removed? It does create overhead, but i think much harm can be done with only a text too.

**Comment by horazont** [comment]
> Considering this might be rather rare situation, such rooms could be reported and removed? It does create overhead, but i think much harm can be done with only a text too.

See the third point from the second enumeration in my first comment in this issue:

> The manpower to deal with abuse.

I don’t want to find myself in the situation of having to moderate that queue. Whitelisting is easier, because no harm is done (to me, anyways) when I don’t process the whitelist queue fast enough. (And the other points from the enumeration still have to be considered.)
