### ISSUE TITLE
Add Access-Control-Allow-Origin header to allow CORS requests

### ISSUE THREAD

**Issue by jcbrand** [horazont/muchopper#69]
When making a [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) request to https://search.jabber.network from the browser, the following error is returned:

_Access to fetch at 'https://search.jabber.network/api/1.0/rooms' from origin 'http://localhost:8008' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled._

Looks like you need to add a 'Access-Control-Allow-Origin'  response header to allow websites hosted at other domains to make requests to search.jabber.network.

**Comment by jcbrand** [comment]
CC @Pawbud

**Comment by horazont** [comment]
I decided to solve this on the webserver level instead of on the application level.

The `/api/` URL subtree now has `Access-Control-Allow-Origin: *` set, as is intended:

<pre>
curl -vvv -XOPTIONS https://search.jabber.network/api/1.0/search
*   Trying 2a01:4f9:2b:2c50::1:7:443...
* Connected to search.jabber.network (2a01:4f9:2b:2c50::1:7) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=search.jabber.network
*  start date: Apr  4 00:42:33 2022 GMT
*  expire date: Jul  3 00:42:32 2022 GMT
*  subjectAltName: host "search.jabber.network" matched cert's "search.jabber.network"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
> OPTIONS /api/1.0/search HTTP/1.1
> Host: search.jabber.network
> User-Agent: curl/7.82.0
> Accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Tue, 19 Apr 2022 15:40:01 GMT
< Server: Apache/2.4.38 (Debian)
< X-Clacks-Overhead: GNU Terry Pratchett
< Content-Type: text/html; charset=utf-8
< Allow: OPTIONS, POST, HEAD, GET
< Content-Length: 0
< Vary: Accept-Encoding
< Access-Control-Allow-Origin: *
<
* Connection #0 to host search.jabber.network left intact
</pre>

Please confirm that it works for you so that I can close this issue.

**Comment by PawBud** [comment]
@horazont  So, I tried both:-
```
const url = "https://search.jabber.network/docs/api/1.0/rooms";
    const response = await fetch(url);
    var data = await response.json();
    console.log(data);
```
```
const url = "https://search.jabber.network/docs/api/1.0/rooms";
    const response = await fetch(url, {
        mode: 'cors',
        headers: {
            'Access-Control-Allow-Origin': '*'
        }
    });
    
    var data = await response.json();
    console.log(data);
```

Getting the Same error:-
<img width="496" alt="Screen Shot 2022-04-20 at 11 52 27 AM" src="https://user-images.githubusercontent.com/48093317/164163629-5a76014b-2d46-4965-bbee-061530e087b1.png">

**Comment by jcbrand** [comment]
Thanks @horazont 

Works for me, I get a 200 response when calling `await fetch('https://search.jabber.network/api/1.0/rooms')`

@PawBud

`Access-Control-Allow-Origin` is a response header, it doesn't make sense to set it as a request header as you do in your second example.

**Comment by PawBud** [comment]
> Thanks @horazont
> 
> Works for me, I get a 200 response when calling `await fetch('https://search.jabber.network/api/1.0/rooms')`
> 
> @PawBud
> 
> `Access-Control-Allow-Origin` is a response header, it doesn't make sense to set it as a request header as you do in your second example.

right, I still tried it as a request header as someone on Stack overflow had recommended it :/. Nevertheless, @jcbrand the fetch API should work when the URL is passed, right?

**Comment by PawBud** [comment]
Update:- @horazont This issue can be closed It worked.

**Comment by horazont** [comment]
Perfect, thanks!
